# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20171130_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Serie')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
    ]
