# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20171130_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Actividad')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
            },
        ),
    ]
