# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Perfil')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'Usuarios de Proyecto',
                'db_table': 'usuario_proyecto',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuarioproyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Usuario'),
        ),
    ]
